export const DEFAULT_PORT = 4000
export const DEFAULT_QUEUE_MAX_SIZE = 10
export const DEFAULT_QUEUE_MAX_CONCURRENT = 1
export const DEFAULT_SHUTDOWN_TIMEOUT_MS = 10_000
export const DEFAULT_REGISTRY_MAX_ENTRIES = 50
export const DEFAULT_REGISTRY_MAX_VULNS_PER_SCAN = 10_000
export const DEFAULT_RETRY_AFTER_SECONDS = 30
